version: '3.9'

services:

  db:
    container_name: db
    image: postgres
    volumes:
      - .:/app
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./backend
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - ./backend:/app/backend
      - static:/app/backend/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "CHOKIDAR_USEPOLLING=true"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - .:/app
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - "CHOKIDAR_USEPOLLING=true"

volumes:
  postgres-data:
  static: