version: '3.9'

services:

  db:
    container_name: db
    image: postgres
    volumes:
      - .:/app
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
  backend:
    container_name: backend
    build: ./backend
    command: ./entrypoint.sh
    volumes:
      - ./backend:/app/backend
      - static:/app/backend/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "CHOKIDAR_USEPOLLING=true"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - .:/app
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
    # responsible for watching file changes
      - "CHOKIDAR_USEPOLLING=true"
volumes:
  postgres-data:
  static:
