# Generated by Django 3.1.8 on 2022-01-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210417_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Successful', 'Successful'), ('Reclamation', 'Reclamation')], default='pending'),
        ),
    ]
