# Generated by Django 3.1.8 on 2022-01-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220119_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('created', 'Created'), ('pending', 'Pending'), ('failed', 'Failed'), ('successful', 'Successful'), ('reclamation', 'Reclamation')], default='created'),
        ),
    ]
