# Generated by Django 3.1.7 on 2021-02-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210225_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fabric',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='size',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.variant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='ordering',
            field=models.PositiveIntegerField(),
        ),
    ]
