# Generated by Django 3.1.7 on 2021-02-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210226_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_variant',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='product_images/default_product_image.jpg', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('NA', 'Not Applicable')], default=('NA', 'Not Applicable'), max_length=50),
        ),
    ]
