# Generated by Django 3.1.7 on 2021-02-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210228_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
