# Generated by Django 3.1.7 on 2021-03-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210328_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
