# Generated by Django 3.1.7 on 2021-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210226_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='product_images/default_product_image.png', upload_to='product_images'),
        ),
    ]
